---
language: node_js
node_js:
  - "6"
  - "10"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version
  - node -v

install:
  - npm install
  - bower install

script:
  - COVERAGE=true npm test

after_success:
  - npm run coverage
